"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.kelvinToRoemer = exports.kelvinToReaumur = exports.kelvinToRankine = exports.kelvinToNewton = exports.kelvinToFahrenheit = exports.kelvinToDelisle = exports.kelvinToCelsius = exports.fahrenheitToKelvin = exports.fahrenheitToCelsius = exports.celsiusToKelvin = exports.celsiusToFahrenheit = void 0;
var celsius_fahrenheit_1 = require("./celsius-fahrenheit");
Object.defineProperty(exports, "celsiusToFahrenheit", { enumerable: true, get: function () { return celsius_fahrenheit_1.celsiusToFahrenheit; } });
var celsius_kelvin_1 = require("./celsius-kelvin");
Object.defineProperty(exports, "celsiusToKelvin", { enumerable: true, get: function () { return celsius_kelvin_1.celsiusToKelvin; } });
var fahrenheit_celsius_1 = require("./fahrenheit-celsius");
Object.defineProperty(exports, "fahrenheitToCelsius", { enumerable: true, get: function () { return fahrenheit_celsius_1.fahrenheitToCelsius; } });
var fahrenheit_kelvin_1 = require("./fahrenheit-kelvin");
Object.defineProperty(exports, "fahrenheitToKelvin", { enumerable: true, get: function () { return fahrenheit_kelvin_1.fahrenheitToKelvin; } });
var kelvin_celsius_1 = require("./kelvin-celsius");
Object.defineProperty(exports, "kelvinToCelsius", { enumerable: true, get: function () { return kelvin_celsius_1.kelvinToCelsius; } });
var kelvin_delisle_1 = require("./kelvin-delisle");
Object.defineProperty(exports, "kelvinToDelisle", { enumerable: true, get: function () { return kelvin_delisle_1.kelvinToDelisle; } });
var kelvin_fahrenheit_1 = require("./kelvin-fahrenheit");
Object.defineProperty(exports, "kelvinToFahrenheit", { enumerable: true, get: function () { return kelvin_fahrenheit_1.kelvinToFahrenheit; } });
var kelvin_newton_1 = require("./kelvin-newton");
Object.defineProperty(exports, "kelvinToNewton", { enumerable: true, get: function () { return kelvin_newton_1.kelvinToNewton; } });
var kelvin_rankine_1 = require("./kelvin-rankine");
Object.defineProperty(exports, "kelvinToRankine", { enumerable: true, get: function () { return kelvin_rankine_1.kelvinToRankine; } });
var kelvin_reaumur_1 = require("./kelvin-reaumur");
Object.defineProperty(exports, "kelvinToReaumur", { enumerable: true, get: function () { return kelvin_reaumur_1.kelvinToReaumur; } });
var kelvin_roemer_1 = require("./kelvin-roemer");
Object.defineProperty(exports, "kelvinToRoemer", { enumerable: true, get: function () { return kelvin_roemer_1.kelvinToRoemer; } });
